name: 'Tweet Activity'
description: 'A GitHub Action that will tweet out about certain actions in your repo so everyone following you can be kept updated'
inputs:
  tweet:  # id of input
    description: 'Content of the tweet you wanna make'
    required: true
    default: 'World World'
outputs: 
  tweet-sent:
    description: 'The tweet that got sent out'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: at-sign
  color: blue
